name: sfr_env
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- cffi=1.10.0=py27_0
- cudatoolkit=8.0=3
- cudnn=6.0.21=cuda8.0_0
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.30=1
- libtiff=4.0.6=3
- mkl=2017.0.3=0
- nccl=1.3.4=cuda8.0_1
- numpy=1.13.1=py27_0
- olefile=0.44=py27_0
- openssl=1.0.2l=0
- pillow=4.2.1=py27_0
- pip=9.0.1=py27_1
- pycparser=2.18=py27_0
- python=2.7.13=0
- readline=6.2=2
- scipy=0.19.1=np113py27_0
- setuptools=36.4.0=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - editdistance==0.4
  - opencv-python==3.4.0.12
  - pyclipper==1.1.0
  - pyyaml==3.12
  - svgpathtools==1.3.2
  - torch==0.3.1
  - torchvision==0.2.1

